---

- name: Install dependency packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - unzip
    - build-essential
    - tcl

- name: download redis tar file
  get_url:
    url: "http://download.redis.io/releases/redis-4.0.11.tar.gz"
    dest: /root/redis-4.0.11.tar.gz

- name: unarchive redis
  unarchive:
    src: /root/redis-4.0.11.tar.gz
    dest: /root/
    remote_src: yes

- name: change to redis dir and make
  shell: make
  args:
    chdir: /root/redis-4.0.11

- name: change to redis dir and make
  shell: make install
  args:
    chdir: /root/redis-4.0.11

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ config_dir }}"
    - "{{ pid_dir }}"
    - "{{ log_dir }}"
    - "{{ data_dir }}"
