---

- name: Install dependency packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - unzip
    - build-essential
    - tcl

- name: download redis tar file
  get_url:
    url: "http://download.redis.io/releases/redis-4.0.11.tar.gz"
    dest: /root/redis-4.0.11.tar.gz

- name: unarchive redis
  unarchive:
    src: /root/redis-4.0.11.tar.gz
    dest: /root/
    remote_src: yes

- name: change to redis dir and make
  shell: make
  args:
    chdir: /root/redis-4.0.11

- name: change to redis dir and make
  shell: make install
  args:
    chdir: /root/redis-4.0.11

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ config_dir }}"
    - "{{ pid_dir }}"
    - "{{ log_dir }}"
    - "{{ data_dir }}"

- name: copy redis config to master
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  delegate_to: "{{ groups['redis'][0] }}"
  with_items:
    - {src: 'templates/redis.conf.j2',dest: '{{ config_dir }}/redis.conf'}
    - {src: 'templates/sentinel.conf.j2',dest: '{{ config_dir }}/sentinel.conf'}

- name: copy redis config to slaves
  template:
    src: templates/redis-slave.conf.j2
    dest: "{{ config_dir }}/redis.conf"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['slaves'] }}"

- name: copy sentinel config to slaves
  template:
    src: templates/sentinel-slave.conf.j2
    dest: "{{ config_dir }}/sentinel.conf"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['slaves'] }}"
